<a href="https://colab.research.google.com/github/omarFarooq21/CS102L/blob/main/5x5_image_3x3_kernel_convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
image = torch.tensor(np.array([[10,10,10,10,10], [10,20,20,20,10], [10,20,30,20,10],  [10,20,20,20,10], [10,10,10,10,10]]))
#print(image[:3,:3])
#print(image)

In [2]:
filterx = torch.tensor(np.array([[-1, 0, 1], [-2,0,2], [-1,0,1]]))
filterx

tensor([[-1,  0,  1],
        [-2,  0,  2],
        [-1,  0,  1]])

In [3]:
filtery = torch.tensor(np.array([[-1, -2, -1], [0,0,0], [1,2,1]]))
filtery

tensor([[-1, -2, -1],
        [ 0,  0,  0],
        [ 1,  2,  1]])

In [4]:
def absolute(Gx, Gy):
  return torch.abs(Gx) + torch.abs(Gy)


In [5]:
def convolve(image, filter):  #takes a 5x5 image and a 3x3 filter
  rows, cols = image.shape
  k, l = filter.shape
  output = torch.zeros((3,3))
  for i in range(rows - 2):
    for j in range(cols - 2):
      submatrix = image[i:i+3, j:j+3]
      conv_val = 0
      for x in range(k):
        for y in range(l):
          conv_val += filter[x][y] * submatrix[x][y]
      output[i,j] = conv_val

  return output

In [6]:
outputx = convolve(image, filterx)
outputx


tensor([[ 40.,   0., -40.],
        [ 60.,   0., -60.],
        [ 40.,   0., -40.]])

In [8]:
outputy = convolve(image, filtery)
outputy


tensor([[ 40.,  60.,  40.],
        [  0.,   0.,   0.],
        [-40., -60., -40.]])

In [10]:
abs = absolute(outputx, outputy)
abs

tensor([[80., 60., 80.],
        [60.,  0., 60.],
        [80., 60., 80.]])